version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "~/.aerokube/selenoid/:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8084:8080"
    depends_on:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
  mytest:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    links:
      - selenoid
    depends_on:
      - selenoid
      - selenoid-ui
    volumes:
      - report_volume:/tests
  myreport:
    build:
      context: .
      dockerfile: DockerAllure
    network_mode: bridge
    ports:
      - "8082:8081"
    depends_on:
      - mytest
    volumes:
      - report_volume:/tests
  mylocust:
    build:
      context: .
      dockerfile: DockerLocust
    network_mode: bridge
    ports:
      - "8083:8086"
    depends_on:
      - mytest
volumes:
  report_volume: {}